### ISSUE TITLE
Copy editor nitpickiness

### ISSUE THREAD

**Issue by phiala** [guerrillawfc/alternate-schedule#2]
Some sections have smart quotes, other straight quotes. Which do you want?

**Comment by pablodefendini** [comment]
Smart quotes, most definitely. I did a smart quote/apostrophe pass this morning, but was waiting to get the whole thing in before doing another.

**Comment by phiala** [comment]
Okay, then I'll leave it for now. 

This is obviously a programmer vs designer thing!
